Add one-to-one relation
dcsaorg/DCSA-Core pull request #73
Opened 2021-05-25 13:06 UTC by multimikael

Support one-to-one relations using @ForeignKey on models.

2021-05-25 14:50 UTC, HenrikHL commented
In general I am ok with this PR. I would though have turned the @ForeignKey annotation around and placed it on the object that needs to be "expanded/filled" instead of on the id... This would allow for combined keys as well - I cannot see how that can be done in the current suggestion...

2021-05-26 07:11 UTC, nt-as requested changes

2021-05-26 07:11 UTC, nt-as commented on src/main/java/org/dcsa/core/repository/RowMapper.java
> +    public static <T> T mapRow(Row row, RowMetadata metadata, DBEntityAnalysis<T> dbEntityAnalysis, Class<T> modelClass, boolean ignoreUnknownProperties) {
I think we should make this "non-static" and initialize the object mapper as field.  Something like:

```java
    private final ObjectMapper objectMapper = new ObjectMapper()
                   .registerModule(new JavaTimeModule()) // Needed to process time objects.
                   .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
                   .disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE)
                   .enable(SerializationFeature.WRITE_DATES_WITH_ZONE_ID)
                   .setAnnotationIntrospector(new JacksonAnnotationIntrospector() {
                      // Insert body here - too lazy to copy-waste it as multiline copy in GH embeds HTML fragments ...
                   });
```

2021-05-26 07:15 UTC, nt-as commented
> 
> 
> In general I am ok with this PR. I would though have turned the @foreignkey annotation around and placed it on the object that needs to be "expanded/filled" instead of on the id... This would allow for combined keys as well - I cannot see how that can be done in the current suggestion...

To be honest, I prefer having it here it is and I am discussing the pros/cons with Henrik.

2021-05-26 07:28 UTC, nt-as commented
We agreed that the FK annotation is fine where it is.  :)

2021-05-26 07:35 UTC, HenrikHL commented
> We agreed that the FK annotation is fine where it is. :)

Yes - we will keep it as it is :-) And expand if needed in the future

2021-05-26 20:24 UTC, HenrikHL commented
Before we merge this - Core version needs to be bumped ;-)

2021-05-28 12:36 UTC, nt-as approved these changes

2021-05-31 08:45 UTC, nt-as approved these changes

2021-05-31 08:49 UTC, nt-as commented
@HenrikHL: Can you force this one through? Our CI fails because the PR is from an external repo and therefore does not have access to the secret to publish artifacts at the end of the tests.

2021-05-31 09:02 UTC, merged

2021-05-31 09:02 UTC, HenrikHL commented
merged...